---
services:

    # Self
    ez.launchpad.self_update:
        class: eZ\Launchpad\Command\SelfUpdate
        calls:
            - [setParameters, [ {env: "%app_env%", url: "%ez_phar%", version: "%ez_phar_version%"}] ]
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.self_rollback:
        class: eZ\Launchpad\Command\Rollback
        tags:
            - { name: ezlaunchpad.command }

    # Docker Actions
    ez.launchpad.initialize:
        class: eZ\Launchpad\Command\Initialize
        arguments:
            - "@ezlaunchpad_project.information.dumper"
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'ez_install', 'ez_install_solr' ] ] ]
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.create:
        class: eZ\Launchpad\Command\Create
        arguments:
            - "@ezlaunchpad_project.information.dumper"
        calls:
            - [setRequiredRecipes, [ [ 'composer_install', 'ez_create', 'import_dump', 'ez_install_solr' ] ] ]
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.start:
        class: eZ\Launchpad\Command\Start
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.build:
        class: eZ\Launchpad\Command\Build
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.up:
        class: eZ\Launchpad\Command\Up
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.stop:
        class: eZ\Launchpad\Command\Stop
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.remove:
        class: eZ\Launchpad\Command\Remove
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.clean:
        class: eZ\Launchpad\Command\Clean
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.status:
        class: eZ\Launchpad\Command\Status
        arguments:
            - "@ezlaunchpad_project.information.dumper"
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.enter:
        class: eZ\Launchpad\Command\Enter
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.logs:
        class: eZ\Launchpad\Command\Logs
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.dumpdata:
        class: eZ\Launchpad\Command\DumpData
        calls:
            - [setRequiredRecipes, [ [ 'create_dump' ] ] ]
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.importdata:
        class: eZ\Launchpad\Command\ImportData
        calls:
            - [setRequiredRecipes, [ [ 'import_dump' ] ] ]
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.sfrun:
        class: eZ\Launchpad\Command\SymfonyRun
        tags:
            - { name: ezlaunchpad.command }

    ez.launchpad.comprun:
        class: eZ\Launchpad\Command\ComposerRun
        tags:
            - { name: ezlaunchpad.command }
